version: '2'
catalog:
  name: Home Assistant
  version: v2
  description: |
    Home Assistant is an open-source home automation platform running on Python 3. Track and control all devices at home and automate control.
  questions:
    - variable: HASS_CONFIG
      label: Hass config
      description: Where the hass config is stored
      required: true
      default: hass-config
      type: string
    - variable: ENABLE_AIRSONOS
      label: Enable AirSonos?
      required: true
      default: false
      type: boolean
    - variable: ENABLE_HOMEBRIDGE
      label: Enable HomeBridge?
      required: true
      default: false
      type: boolean
    - variable: HOMEBRIDGE_CONFIG
      label: HomeBridge config
      description: Where the homebridge config is stored
      default: homebridge-config
      type: string


services: 
  hass:
    scale: 1
    health_check:
      port: 8123
      interval: 5000
      unhealthy_threshold: 3
      # request_line: GET /api/ HTTP/1.0
      healthy_threshold: 2
  airsonos:
    scale: 1
  homebridge:
    scale: 1
