version: '2'
catalog:
  name: Mayan EDMS
  version: v1
  description: |
    Mayan EDMS is an electronic vault for your documents. With Mayan EDMS you will never lose another document to floods, fire, theft, sabotage, fungus or decomposition. Its advanced search and categorization capabilities will help you reduce the time to find the information you need. It is free open source and integrates with your existing equipment, that means low to no initial investment, and even lower total cost of ownership, reducing operational costs has never been this easy. Being open source its code is freely available, allowing you to see how it is handling your documents if you ever need to, you will be glad you choose Mayan EDMS on your next audit. Initially released in 2011 and with thousands of installations worldwide, Mayan EDMS is a mature and time tested software you can rely on.
  questions:
    - variable: MAYAN_DATA
      label: Where to store the data
      required: true
      type: string
      default: mayan-data
    - variable: INFLUXDB_VERSION
      label: Version
      description: What version of Influxdb to run
      required: true
      type: enum
      default: "alpine"
      options:
        - "alpine"
        - "latest"
        - "1.3-alpine"
        - "1.3.7-alpine"
        - "1.3.6-alpine"
        - "1.3.5-alpine"
        - "1.3.4-alpine"
        - "1.3.3-alpine"
        - "1.3.2-alpine"
        - "1.3.1-alpine"
        - "1.3.0-alpine"
        - "1.2-alpine"
        - "1.1-alpine"
        - "1.0-alpine"

services:
  mayan:
    scale: 1
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      interval: 2000

