version: '2'
services:
  znc:
    labels:
      io.rancher.container.sidekicks: znc-makeconfig
    tty: false
    image: znc
    volumes:
      - ${znc_data}:/znc-data
    ports:
      - ${irc_port}:6697/tcp