version: '2'
catalog:
  name: Home Assistant
  version: v1
  description: |
    Home Assistant is an open-source home automation platform running on Python 3. Track and control all devices at home and automate control.
  questions:
    - variable: HASS_CONFIG
      label: Hass config
      description: Where the hass config is stored
      required: true
      default: hass-config
      type: string
    # - variable: ENABLE_APPDAEMON
    #   label: Enable AppDaemon?
    #   required: true
    #   type: 
    # - variable: APPD_HASS_KEY
    #   label: Hass Key
    #   description: Hass access key
    #   required: false
    #   type: password


services: 
  hass:
    scale: 1
    health_check:
      port: 8123
      interval: 5000
      unhealthy_threshold: 3
      # request_line: GET /api/ HTTP/1.0
      healthy_threshold: 2
  # appdaemon:
  #   scale: 1