name: Home Assistant
description: |
  Home Assistant is an open-source home automation platform running on Python 3. Track and control all devices at home and automate control.
version: v1
category: IoT